#!/bin/bash

# get the directory of THIS script
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# set the JUPYTER_CONFIG_DIR and IPYTHONDIR environment variables to point to
# the Python-2.7 directory
IPY_D=${DIR}/'Python-2.7'
export JUPYTER_CONFIG_DIR=${IPY_D}
export IPYTHONDIR=${IPY_D}

# launch the Introduction notebook
ipython notebook Introduction.ipynb
